In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

dataset = pd.read_csv('Iris.csv')
dataset

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [2]:
# input
x = dataset[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
 
# output
y = dataset['Species']
y.replace(to_replace=['Iris-setosa', 'Iris-versicolor','Iris-virginica'], value=[1, 2, 3], inplace=True)

In [3]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(
        x, y, test_size = 0.25, random_state = 42)

In [4]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)
 
print (xtrain[0:10, :])

[[-1.01827123  1.30636523 -1.39489006 -1.35865217]
 [-0.7730102   2.46390403 -1.33696359 -1.49272181]
 [-0.03722712 -0.77720463  0.74838929  0.92053173]
 [ 0.20803391  0.8433497   0.40083048  0.51832281]
 [ 1.06644751  0.14882642  0.51668341  0.38425317]
 [-0.52774918  2.00088851 -1.45281653 -1.09051288]
 [-0.52774918  1.53787299 -1.33696359 -1.35865217]
 [-0.40511866 -1.47172791 -0.06258127 -0.28609504]
 [ 0.57592545 -0.54569687  0.74838929  0.38425317]
 [ 0.69855596  0.14882642  0.98009517  0.78646209]]


In [5]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(xtrain, ytrain)

GaussianNB()

In [6]:
y_pred = classifier.predict(xtest)

In [7]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, y_pred)
 
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [8]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(ytest, y_pred))

Accuracy :  1.0
